"""fix record models

Revision ID: 1ebef2a68233
Revises: b5f7e635b962
Create Date: 2025-10-28 09:56:46.784293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ebef2a68233'
down_revision: Union[str, Sequence[str], None] = 'b5f7e635b962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
