"""make_reminder_date_optional

Revision ID: 524600c9d0a9
Revises: 7d62760c955d
Create Date: 2025-10-23 20:21:53.396543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '524600c9d0a9'
down_revision: Union[str, Sequence[str], None] = '7d62760c955d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('habits', 'reminder_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('habits', 'reminder_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
