name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: habitdb_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for postgres..."
            sleep 2
          done

      - name: Apply Alembic migrations
        env:
          SECRET_KEY: "abcd"
          ALGORITHM: "HS256"
          ACCESS_TOKEN_EXPIRE_MINUTES: 30
          DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/habitdb_test
        run: |
          alembic upgrade head

      - name: Run tests
        env:
          SECRET_KEY: "abcd"
          ALGORITHM: "HS256"
          ACCESS_TOKEN_EXPIRE_MINUTES: 30
          DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/habitdb_test
        run: |
          pytest -v --asyncio-mode=auto
